RuleFile=/etc/usbguard/rules.conf
RuleFolder=/etc/usbguard/rules.d/
ImplicitPolicyTarget=block
PresentDevicePolicy=apply-policy
InsertedDevicePolicy=block
RestoreControllerDeviceState=true
IPCAllowedUsers=root
IPCAllowedGroups=wheel
AuditBackend=FileAudit
AuditFilePath=/var/log/usbguard/usbguard-audit.log
