#!/usr/bin/env python3
"""Generates everything the Calmo tokens drive.

    generate.py css | cosmic | icons | all     write calmo/generated/
    generate.py --check                        fail when generated/ differs from the tokens
    generate.py wallpaper <variant> <w> <h> <out.png>

The wallpaper is rendered at package build time and is not committed.
"""
import hashlib
import json
import math
import string
import sys
from pathlib import Path

import png
import tokens as tk
from color import over, to_hex

HERE = Path(__file__).resolve().parent
OUT = HERE / "generated"
HEADER = "/* Generated by system/athanor-style/calmo/generate.py from tokens.toml. Do not edit. */\n"


# ---------------------------------------------------------------- GTK CSS

def _css_color(color):
    r, g, b = (round(c * 255) for c in color[:3])
    if color[3] == 1.0:
        return "#%02x%02x%02x" % (r, g, b)
    return f"rgba({r}, {g}, {b}, {color[3]:g})"


def _num(value):
    return f"{value:g}"


def template_values(tokens):
    hearth = tokens["hearth"]
    values = {"font_family": tokens["font"]["family"], "font_features": tokens["font"]["features"],
              "hearth_x": _num(hearth["center"][0] * 100), "hearth_y": _num(hearth["center"][1] * 100),
              "hearth_angle": _num(hearth["gradient_angle"])}
    for index, radius in enumerate(hearth["radii"], 1):
        values[f"hearth_r{index}"] = _num(radius * 100)
        # A 0.12 % ramp, as in the mockup, is the anti-aliased edge of the disc.
        values[f"hearth_e{index}"] = _num(round(radius * 100 + 0.12, 2))
    values.update({f"radius_{k}": _num(v) for k, v in tokens["radius"].items()})
    values.update({f"size_{k}": _num(v) for k, v in tokens["size"].items()})
    return values


def css(tokens, variant):
    palette = tk.colors(tokens, variant)
    lines = [HEADER, f"/* Variant: {variant} */\n"]
    lines += [f"@define-color ath_{name} {_css_color(palette[name])};\n" for name in sorted(palette)]
    template = string.Template((HERE / "templates" / "surfaces.css.in").read_text(encoding="utf-8"))
    return "".join(lines) + "\n" + template.substitute(template_values(tokens))


# ---------------------------------------------------------------- COSMIC inputs

# Builder input <- token. Semantics read in cosmic-theme's ThemeBuilder::build().
COSMIC_INPUTS = {"accent": "acc", "bg_color": "bg1", "primary_container_bg": "surf",
                 "neutral_tint": "ink3", "text_tint": "ink"}


def cosmic_inputs(tokens):
    modes = {}
    for mode in ("light", "dark"):
        palette = tk.colors(tokens, mode)
        modes[mode] = {key: [round(c, 6) for c in palette[name][:3]] for key, name in COSMIC_INPUTS.items()}
    return json.dumps(modes, indent=2, sort_keys=True) + "\n"


def cosmic_background():
    """cosmic-bg's two default keys, in RON."""
    entry = ('(\n    output: "all",\n    source: Path("/usr/share/backgrounds/athanor/hearth-light.png"),\n'
             "    filter_by_theme: false,\n    rotation_frequency: 3600,\n    filter_method: Lanczos,\n"
             "    scaling_mode: Zoom,\n    sampling_method: Alphanumeric,\n)\n")
    return {"all": entry, "same-on-all": "true\n"}


# ---------------------------------------------------------------- seal icons

MARK = ('<path fill-rule="evenodd" d="M12 1.6a10.4 10.4 0 1 0 0 20.8a10.4 10.4 0 1 0 0-20.8z'
        'M12 3.4a8.6 8.6 0 1 1 0 17.2a8.6 8.6 0 1 1 0-17.2z"/>'
        '<path d="M12 6.2c2.3 2.7 3.8 4.6 3.8 6.9a3.8 3.8 0 0 1-7.6 0c0-2.3 1.5-4.2 3.8-6.9z"/>')
BADGE_CENTER, BADGE_RADIUS = (17.5, 17.5), 6.5


def _polygon(points):
    cx, cy = BADGE_CENTER
    return "M" + "L".join(f"{_num(round(cx + x, 3))} {_num(round(cy + y, 3))}" for x, y in points) + "z"


def _check_glyph(width=1.7):
    """The outline of a two-segment stroke with a mitred elbow, as one polygon."""
    a, b, c = (-3.2, 0.2), (-1.0, 2.4), (3.3, -2.3)

    def normal(p, q):
        dx, dy = q[0] - p[0], q[1] - p[1]
        length = math.hypot(dx, dy)
        return (-dy / length * width / 2, dx / length * width / 2)

    n1, n2 = normal(a, b), normal(b, c)

    def miter(sign):
        # Intersection of the two offset lines on one side of the elbow.
        p = (a[0] + sign * n1[0], a[1] + sign * n1[1])
        q = (c[0] + sign * n2[0], c[1] + sign * n2[1])
        d1, d2 = (b[0] - a[0], b[1] - a[1]), (b[0] - c[0], b[1] - c[1])
        t = ((q[0] - p[0]) * d2[1] - (q[1] - p[1]) * d2[0]) / (d1[0] * d2[1] - d1[1] * d2[0])
        return (p[0] + t * d1[0], p[1] + t * d1[1])

    return [(a[0] + n1[0], a[1] + n1[1]), miter(1), (c[0] + n2[0], c[1] + n2[1]),
            (c[0] - n2[0], c[1] - n2[1]), miter(-1), (a[0] - n1[0], a[1] - n1[1])]


def _cross_glyph(half=0.85, arm=3.3):
    plus = [(-half, -arm), (half, -arm), (half, -half), (arm, -half), (arm, half), (half, half),
            (half, arm), (-half, arm), (-half, half), (-arm, half), (-arm, -half), (-half, -half)]
    k = math.sqrt(0.5)
    return [((x - y) * k, (x + y) * k) for x, y in plus]


def _bang_glyphs():
    return [[(-0.9, -3.7), (0.9, -3.7), (0.9, 1.0), (-0.9, 1.0)],
            [(-0.9, 2.1), (0.9, 2.1), (0.9, 3.7), (-0.9, 3.7)]]


# state -> (GTK symbolic class, glyph polygons). Three shapes, three colours (SH12).
SEALS = {"verified": ("success", [_check_glyph()]), "attention": ("warning", _bang_glyphs()),
         "blocked": ("error", [_cross_glyph()])}


def _svg(body):
    return ('<?xml version="1.0" encoding="UTF-8"?>\n<!-- Generated by calmo/generate.py. Do not edit. -->\n'
            f'<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24">{body}</svg>\n')


def icons():
    cx, cy = BADGE_CENTER
    r = BADGE_RADIUS
    disc = f"M{_num(cx - r)} {_num(cy)}a{_num(r)} {_num(r)} 0 1 0 {_num(2 * r)} 0a{_num(r)} {_num(r)} 0 1 0 {_num(-2 * r)} 0z"
    files = {"athanor-mark-symbolic.svg": _svg(MARK)}
    for state, (css_class, glyphs) in SEALS.items():
        badge = f'<path class="{css_class}" fill-rule="evenodd" d="{disc}{"".join(_polygon(g) for g in glyphs)}"/>'
        files[f"athanor-seal-{state}-symbolic.svg"] = _svg(MARK + badge)
    return files


# ---------------------------------------------------------------- hearth wallpaper

def hearth_rows(tokens, variant, width, height, block=16):
    """Rows of RGB bytes. Exact at every disc edge, constant over runs of at most `block`
    pixels elsewhere: at 3840 px the gradient moves by under 0.03 of an 8-bit level in 16
    pixels, and a 4K frame renders in 2.5 s instead of minutes."""
    palette = tk.colors(tokens, variant)
    hearth = tokens["hearth"]
    cx, cy = hearth["center"][0] * width, hearth["center"][1] * height
    reach = max(math.hypot(cx - x, cy - y) for x in (0, width) for y in (0, height))
    discs = [(palette[f"d{i}"], r * reach) for i, r in reversed(list(enumerate(hearth["radii"], 1)))]
    angle = math.radians(hearth["gradient_angle"])
    ax, ay = math.sin(angle), -math.cos(angle)
    length = abs(width * ax) + abs(height * ay)
    bg1, bg2 = palette["bg1"], palette["bg2"]

    def pixel(x, y):
        t = min(1.0, max(0.0, ((x + 0.5 - width / 2) * ax + (y + 0.5 - height / 2) * ay) / length + 0.5))
        color = tuple(p + (q - p) * t for p, q in zip(bg1[:3], bg2[:3])) + (1.0,)
        distance = math.hypot(x + 0.5 - cx, y + 0.5 - cy)
        for disc, radius in discs:
            coverage = min(1.0, max(0.0, radius - distance + 0.5))
            if coverage:
                color = over(disc[:3] + (disc[3] * coverage,), color)
        return bytes(round(c * 255) for c in color[:3])

    for y in range(height):
        edges = set()
        for _, radius in discs:
            dy = y + 0.5 - cy
            if abs(dy) < radius + 1:
                half = math.sqrt(max(0.0, (radius + 1) ** 2 - dy * dy))
                inner = math.sqrt(max(0.0, (radius - 1) ** 2 - dy * dy)) if abs(dy) < radius - 1 else 0.0
                for lo, hi in ((cx - half, cx - inner), (cx + inner, cx + half)):
                    edges.update(range(max(0, int(lo) - 1), min(width, int(hi) + 2)))
        row = bytearray()
        x = 0
        while x < width:
            if x in edges:
                row += pixel(x, y)
                x += 1
                continue
            end = min(width, (x // block + 1) * block)
            stop = x + 1
            while stop < end and stop not in edges:
                stop += 1
            row += pixel((x + stop - 1) // 2, y) * (stop - x)
            x = stop
        yield bytes(row)


def wallpaper(tokens, variant, width, height):
    return png.encode(width, height, hearth_rows(tokens, variant, width, height))


# ---------------------------------------------------------------- files and --check

def generated_files(tokens):
    """{path relative to generated/: text}. Everything committed; not the wallpaper and
    not generated/cosmic/, which COSMIC's own code derives (forge/tools/calmo-cosmic-theme)."""
    files = {f"css/calmo-{v}.css": css(tokens, v) for v in tk.VARIANTS}
    files["cosmic-inputs.json"] = cosmic_inputs(tokens)
    files.update({f"cosmic-bg/com.system76.CosmicBackground/v1/{k}": v for k, v in cosmic_background().items()})
    files.update({f"icons/{name}": text for name, text in icons().items()})
    return files


def check(tokens, out=OUT):
    problems = []
    for name, text in generated_files(tokens).items():
        path = out / name
        if not path.exists():
            problems.append(f"{name}: missing, run generate.py all")
        elif path.read_text(encoding="utf-8") != text:
            problems.append(f"{name}: differs from the tokens, run generate.py all")
    stamp = out / "cosmic" / "STAMP"
    wanted = hashlib.sha256(cosmic_inputs(tokens).encode()).hexdigest()
    if not stamp.exists():
        problems.append("cosmic/STAMP: missing, run forge/tools/calmo-cosmic-theme/derive.sh")
    elif stamp.read_text(encoding="utf-8").strip() != wanted:
        problems.append("cosmic/: derived from other inputs, run forge/tools/calmo-cosmic-theme/derive.sh")
    return problems


def main(argv):
    tokens = tk.load()
    if argv == ["--check"]:
        problems = check(tokens)
        print("\n".join(problems) if problems else "generated/ matches tokens.toml")
        return 1 if problems else 0
    if len(argv) == 5 and argv[0] == "wallpaper":
        Path(argv[4]).write_bytes(wallpaper(tokens, argv[1], int(argv[2]), int(argv[3])))
        return 0
    prefixes = {"css": ("css/",), "cosmic": ("cosmic-inputs.json", "cosmic-bg/"), "icons": ("icons/",),
                "all": ("",)}
    if len(argv) != 1 or argv[0] not in prefixes:
        print(__doc__)
        return 2
    for name, text in generated_files(tokens).items():
        if name.startswith(prefixes[argv[0]]):
            path = OUT / name
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_text(text, encoding="utf-8")
            print(f"wrote {path.relative_to(HERE)}")
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
